Task 1
XRicko/altexsoft-lab-2020 pull request #1
Opened 2020-08-01 22:55 UTC by XRicko

2020-08-03 14:26 UTC, alex-geraschenko requested changes
Пожалуйста, вынесите каждую задачу в отдельный класс в соответствии с принципами SOLID.

Вообще курс по **.NET Core**

2020-08-03 14:26 UTC, alex-geraschenko commented on ConsoleApp1/Program.cs
> +                                    string replaced = TextManager.RemoveSymbols(text, symbols);
Зачем 2 раза вызывать одно и тоже?

2020-08-03 14:26 UTC, alex-geraschenko commented on ConsoleApp1/Program.cs
> +                                string[] words = noPunct.Split(new string[] { " ", "\n", "\r" }, StringSplitOptions.RemoveEmptyEntries);
Обратите внимание на регулярные выражения

2020-08-03 14:26 UTC, alex-geraschenko commented on ConsoleApp1/Program.cs
> +                                Console.WriteLine($"{nthSentence} sentence backwards: " + TextManager.ReverseString(sentences[nthSentence - 1]) + "\n");
Задача выполнена не правильно

2020-08-07 16:04 UTC, XRicko commented on ConsoleApp1/Program.cs
> +                                    string replaced = TextManager.RemoveSymbols(text, symbols);
Насчёт .Net Core. Просто когда я начилал делать это задание, у меня не было возможности загрузить инструменты для разработки на .Net Core. Сейчас уже установил, следующее задание будет на нем

2020-08-07 16:08 UTC, XRicko commented
> Вообще курс по **.NET Core**

Просто когда я начинал делать это задание, у меня не было возможности загрузить инструменты для разработки на .Net Core. Сейчас уже скачал, следующие задания будут на нем

2020-08-12 13:34 UTC, alex-geraschenko approved these changes

2020-08-12 13:34 UTC, alex-geraschenko commented on ConsoleApp1/UI/ConsoleMessages.cs
> +    class ConsoleMessages
Если все методы класса статические, то и класс лучше сделать статическим

2020-08-12 17:26 UTC, merged