create
XRicko/altexsoft-lab-2020 pull request #3
Opened 2020-08-20 09:53 UTC by XRicko

2020-08-21 19:26 UTC, serhii-shkodenko requested changes

2020-08-21 19:26 UTC, serhii-shkodenko commented on task2/RecipeBook.BL/Controllers/CategoryController.cs
> +        public List<Category> Categories { get; }
Контроллеру не стоит хранить данные, его задача - обратиться за ними в репозиторий. Поэтому постарайтесь реализовать паттерн `Repository` и `UnitOfWork` и обновить логику методов всех контроллеров.

2020-08-21 19:26 UTC, serhii-shkodenko commented on task2/RecipeBook.BL/Models/ModelBase.cs
> +            if (String.IsNullOrWhiteSpace(name))
Общепринятым является использование псевдонима для типа, если он есть.

2020-08-21 19:26 UTC, serhii-shkodenko commented on task2/RecipeBook.UI/Program.cs
> +            int steps = Convert.ToInt32(Dialog("Enter amount of steps to cook this dish: "));
Вы уже знаете, как использовать TryParse(), поэтому используйте либо этот метод, либо добавьте обработку исключения, если пользователь введет некорректные данные.

2020-08-21 19:26 UTC, serhii-shkodenko commented on task2/RecipeBook.UI/Program.cs
> +            for (int i = 0; i < instruction.Capacity; i++)
Вам не нужен ни `List`, ни  `Capacity`.

2020-08-21 19:26 UTC, serhii-shkodenko commented on task2/RecipeBook.BL/Models/Category.cs
> +                ParentID = parentId;
Выберите один вариант для использования в именах идентификаторов: либо ID, либо Id. Код должен быть консистентным.

2020-08-22 11:47 UTC, XRicko commented on task2/RecipeBook.BL/Models/ModelBase.cs
> +            if (String.IsNullOrWhiteSpace(name))
Я гуглил как-то насчет этого и нашел такой вот [ответ](https://stackoverflow.com/a/7077). В [документации](https://docs.microsoft.com/en-us/dotnet/api/system.string.isnullorwhitespace?view=netcore-3.1) от Microsoft тоже есть примеры именно со `String`. Хотя Visual Studio таки предлагала сменить на `string`

2020-08-22 11:52 UTC, XRicko commented on task2/RecipeBook.BL/Models/Category.cs
> +                ParentID = parentId;
Да, это, скорее всего, просто опечатка/невнимательность

2020-08-22 19:45 UTC, XRicko commented on task2/RecipeBook.UI/Program.cs
> +            for (int i = 0; i < instruction.Capacity; i++)
Поменял на массив из `string`. Правильно?

2020-08-26 12:57 UTC, alex-geraschenko requested changes

2020-08-26 12:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Controllers/ControllerBase.cs
> +        internal UnitOfWork unitOfWork = new UnitOfWork();
1. Нарушение принципа **Dependency Inversion**
2. Поле лучше сделать `protected` и заменить на `readonly` свойство, чтобы не нарушать принцип **Open-Closed**
3. Имена для не приватных свойств принято называть в `PascalCase`

2020-08-26 12:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Controllers/CategoryController.cs
> +            var category = unitOfWork.Categories.Get(ref name);
Зачем выбирать сущность, есть метод должен ее создавать?

2020-08-26 12:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Controllers/IngredientController.cs
> +            var ingredient = unitOfWork.Ingredients.Get(ref name);
Зачем выбирать сущность, есть метод должен ее создавать?

2020-08-26 12:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Controllers/JSONDataManager.cs
> +            var serializer = new JsonSerializer();
Нарушение принципа **Dependency Inversion**

2020-08-26 12:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Controllers/JSONDataManager.cs
> +            var serializer = new JsonSerializer();
Нарушение принципа **Dependency Inversion**

2020-08-26 12:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Controllers/RecipeController.cs
> +            var recipe = unitOfWork.Recipes.Get(ref name);
Зачем выбирать сущность, есть метод должен ее создавать?

2020-08-26 12:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Controllers/RecipeController.cs
> +            if (unitOfWork.Recipes.Get(recipe) == null)
Условие и текст исключения противоречат друг другу

2020-08-26 12:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Models/Category.cs
> +        public string ParentName { get; }
Зачем дублировать имя категории, если его можно получить по `ParentId`?

2020-08-26 12:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Models/Recipe.cs
> +            if (String.IsNullOrWhiteSpace(description))
Испольщуйте `string` вместо `String`

2020-08-26 12:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Repository/Classes/Repository.cs
> +        private readonly IDataManager manager = new JSONDataManager();
Нарушение принципа **Dependency Inversion**

2020-08-26 12:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Repository/Classes/Repository.cs
> +        public T Get(ref string name)
Постарайтесь не использовать `ref`. Изменение входящих параметров внутри метода, считается дурным тоном

2020-08-26 12:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Repository/Classes/Repository.cs
> +            var item = Get(model);
Зачем выбирать сущность, есть метод должен ее добавлять?

2020-08-26 12:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Repository/Classes/UnitOfWork.cs
> +        private readonly IDataManager manager = new JSONDataManager();
Нарушение принципа **Dependency Inversion**

2020-08-26 12:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Repository/Interfaces/IRepository.cs
> +        T Get(ref string name);
Постарайтесь не использовать ref. Изменение входящих параметров внутри метода, считается дурным тоном

2020-08-26 15:02 UTC, XRicko commented on task2/RecipeBook.BL/Controllers/CategoryController.cs
> +            var category = unitOfWork.Categories.Get(ref name);
Чтобы не создавать то, что уже существует

2020-08-26 15:03 UTC, XRicko commented on task2/RecipeBook.BL/Repository/Classes/Repository.cs
> +            var item = Get(model);
Чтобы не добавлять то, что уже есть

2020-08-26 19:37 UTC, serhii-shkodenko commented on task2/RecipeBook.BL/Models/ModelBase.cs
> +            if (String.IsNullOrWhiteSpace(name))
В то же время анализаторы качества кода [StyleCop содержат правило](https://github.com/DotNetAnalyzers/StylceCopAnalyzers/blob/master/documentation/SA1121.md), предуматривающее использование псевдонимов для типов. Кроме того, четвертая редакция спецификации С# рекомендует тоже использовать псевдонимы вместо полных имен. Хотя самая последняя, пятая, уже не содержит такой рекомендации 🤪. Поэтому я и употребил слово "общепринятый".

2020-08-27 13:50 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Controllers/CategoryController.cs
> +            if (category == null)
Если инвертировать условие, то можно код можно сделать более читаемым:

```
if (category != null)
{
    return category;
}

if (parentName == null)
{
    return new Category(name);
}

parentName = StandardizeName(parentName);
name = name + " " + parentName;

var parent = unitOfWork.Categories.Get(parentName);

if (parent == null)
{
    parent = new Category(parentName);
    AddCategory(parent);
}

return new Category(name, parent.Id);
```

2020-08-27 13:57 UTC, alex-geraschenko requested changes

2020-08-27 13:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Controllers/CategoryController.cs
> +            if (category == null)
Если инвертировать условие, то можно уменьшить вложеность и сделать код более читаемым

2020-08-27 13:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Controllers/CategoryController.cs
> +                if (parentName != null)
Для проверки строк лучше использовать `string.IsNullOrWhiteSpace`

2020-08-27 13:57 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Repository/Classes/Repository.cs
> +            var item = Get(model);
За это должен отвечать контроллер

2020-08-27 16:56 UTC, alex-geraschenko commented on task2/RecipeBook.BL/Controllers/CategoryController.cs
> +            var category = unitOfWork.Categories.Get(ref name);
За это должен отвечать контроллер

2020-08-27 20:01 UTC, alex-geraschenko approved these changes
Выглядит хорошо. Можно мержить

2020-08-27 20:08 UTC, merged