Tasks/task4
XRicko/altexsoft-lab-2020 pull request #5
Opened 2020-09-21 16:01 UTC by XRicko

2020-09-23 16:32 UTC, alex-geraschenko requested changes
1. Пожалуйста, поправьте проект в соответствии с примером в задании
2. Контроллеры должны создаваться через механизм **Dependency Injection**

2020-09-26 18:12 UTC, serhii-shkodenko commented on task4/RecipeBook.Core/Controllers/ControllerBase.cs
> +        protected readonly IUnitOfWork unitOfWork;
Protected поля принято называть в PascalCase.

2020-09-26 18:12 UTC, serhii-shkodenko commented on task4/RecipeBook.Core/Controllers/CategoryController.cs
> +        public async Task<List<Category>> GetCategoriesAsync(int? id)
Я просмотрел стек вызовов и не увидел, зачем Вы возвращаете `List<T>`. С полученным списком Вы не производите никаких операций добавления или удаления. Поэтому здесь будет достаточно вернуть `IEnumerable<T>`, что упростит Ваш код до:
```
public Task<IEnumerable<Category>> GetCategoriesAsync(int? id)
{
     return unitOfWork.Repository.FindAsync<Category>(c => c.ParentId == id);
}
```
Для подобных методов имеет смысл также удалить `await`, следующий перед `return`. Таким образом, компилятор не будет разворачивать машину состояний, а вернет таску, выполнение которой Вы подождете выше по стеку вызовов.

2020-09-26 18:12 UTC, serhii-shkodenko commented on task4/RecipeBook.Core/Controllers/CategoryController.cs
> +        public async Task<List<Category>> GetCategoriesAsync(int? id)
Пожалуйста, просмотрите Весь код и поправьте все подобные методы.

2020-09-26 18:12 UTC, serhii-shkodenko commented on task4/RecipeBook.Core/Controllers/CategoryController.cs
> +            name = StandardizeName(name);
Вы пытаетесь изменить параметр внутри метода. Это неоднозначная практика, которая ведет к усложнению понимания кода. Кроме того, так как строки в C# являются имммутабельными, с данной сигнатурой метода все равно ничего не получится, Вы не измените параметр. 

`GetAsync<Category>(name)` можно переписать как `GetAsync<Category>(StandardizeName(name))`

2020-09-26 19:56 UTC, XRicko commented on task4/RecipeBook.Core/Controllers/ControllerBase.cs
> +        protected readonly IUnitOfWork unitOfWork;
Вычитал в [документации](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/field) Microsoft, что protected поля вообще лучше не использовать. Поменял на свойство

2020-09-29 08:09 UTC, alex-geraschenko requested changes

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Controllers/ControllerBase.cs
> +            UnitOfWork.SaveAsync();
Не хватает `await`

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Controllers/ControllerBase.cs
> +            UnitOfWork.SaveAsync();
Не хватает `await`

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Controllers/RecipeController.cs
> +            UnitOfWork.SaveAsync();
Не хватает `await`

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Core/RecipeBook.Core.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.8" />
Эта зависимость должна быть в `Infrastructure`

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/EfRepository.cs
> +            return await context.Set<T>().ToListAsync();
Тут можно обойтись без `async/await`

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/EfRepository.cs
> +            return await context.Set<T>().Where(predicate).ToListAsync();
Тут можно обойтись без `async/await`

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/EfRepository.cs
> +            await context.Set<T>().AddAsync(entity);
Тут можно обойтись без `async/await`

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/UnitOfWork.cs
> +            await context.SaveChangesAsync();
Тут можно обойтись без `async/await`

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/UnitOfWork.cs
> +        public async void SaveAsync()
Этот метод должен возвращать `Task`

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/EfRepository.cs
> +        protected readonly RecipeBookContext context;
Зачем это поле `protected` ?

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.SharedKernel/BaseEntity.cs
> +    public class BaseEntity
Этот класс дожен быть абстрактным. Конструктор с параметром - `protected`. Пустой конструктор не нужен.

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/RecipeBookContext.cs
> +            modelBuilder.Entity<Category>(entity =>
Конфигурации для сущностей лучше вынести в отдельные файлы, как в примере.

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/RecipeBookContext.cs
> +                    .HasName("UQ__Category__8517B2E01CAD4794")
Имена констреинтов со случайной последовательностью в конце автоматически генерируются SQL Server. Их указывать не нужно.

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/RecipeBookContext.cs
> +                    .HasConstraintName("FK__Category__Parent__28B808A7");
Имена констреинтов со случайной последовательностью в конце автоматически генерируются SQL Server. Их указывать не нужно.

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/RecipeBookContext.cs
> +                    .HasName("UQ__Ingredie__A1B2F1CC445D2F03")
Имена констреинтов со случайной последовательностью в конце автоматически генерируются SQL Server. Их указывать не нужно.

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/RecipeBookContext.cs
> +                    .HasName("UQ__Recipe__9EFE16E92347DBFB")
Имена констреинтов со случайной последовательностью в конце автоматически генерируются SQL Server. Их указывать не нужно.

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/RecipeBookContext.cs
> +                    .HasConstraintName("FK__Recipe__Category__2C88998B");
Имена констреинтов со случайной последовательностью в конце автоматически генерируются SQL Server. Их указывать не нужно.

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/RecipeBookContext.cs
> +                    .HasConstraintName("FK__RecipeIng__Ingre__30592A6F");
Имена констреинтов со случайной последовательностью в конце автоматически генерируются SQL Server. Их указывать не нужно.

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/RecipeBookContext.cs
> +                    .HasConstraintName("FK__RecipeIng__Recip__2F650636");
Имена констреинтов со случайной последовательностью в конце автоматически генерируются SQL Server. Их указывать не нужно.

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/RecipeBookContext.cs
> +    public partial class RecipeBookContext : DbContext
Зачем этот класс помечен `partial`?

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Entities/Category.cs
> +    public partial class Category : BaseEntity
Зачем этот класс помечен `partial`?

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Entities/Ingredient.cs
> +    public partial class Ingredient : BaseEntity
Зачем этот класс помечен `partial`?

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Entities/RecipeIngredient.cs
> +    public partial class RecipeIngredient
Зачем этот класс помечен `partial`?

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Entities/Recipe.cs
> +    public partial class Recipe : BaseEntity
Зачем этот класс помечен `partial`?

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/RecipeBookContext.cs
> +        public RecipeBookContext() { }
Зачем тут пустой конструктор ?

2020-09-29 08:09 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/RecipeBookContext.cs
> +        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
Зачем этот метод ?

2020-09-29 11:37 UTC, XRicko commented on task4/RecipeBook.Infrastructure/Data/EfRepository.cs
> +        protected readonly RecipeBookContext context;
Не знаю. Я просто в интернете где-то видел пример и почему-то у себя написал. Поменял

2020-09-29 13:09 UTC, XRicko commented on task4/RecipeBook.Infrastructure/Data/EfRepository.cs
> +            return await context.Set<T>().ToListAsync();
Тогда надо возвращать `Task<List<T>>`, потому что оно не преобразовывает `Task<List<T>>` в `Task<IEnumerable<T>>`. Или оставлять так

2020-09-29 13:10 UTC, XRicko commented on task4/RecipeBook.Infrastructure/Data/EfRepository.cs
> +            return await context.Set<T>().Where(predicate).ToListAsync();
Та же ситуация с преобразованием

2020-09-29 13:23 UTC, XRicko commented on task4/RecipeBook.Infrastructure/Data/EfRepository.cs
> +            await context.Set<T>().AddAsync(entity);
Не особо понимаю как. Если убрать `async/await` и сделать просто `return`, то пишет, что невозможно преобразовать из `EntityEntry` в `Task`

2020-09-29 14:54 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/EfRepository.cs
> +            return await context.Set<T>().ToListAsync();
Согласен, оставляйте как есть

2020-09-29 14:54 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/EfRepository.cs
> +            return await context.Set<T>().Where(predicate).ToListAsync();
Согласен, оставляйте как есть

2020-09-29 14:54 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/EfRepository.cs
> +            await context.Set<T>().AddAsync(entity);
Согласен, оставляйте как есть

2020-09-29 15:20 UTC, alex-geraschenko requested changes

2020-09-29 15:20 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Controllers/RecipeController.cs
> +            return UnitOfWork.Repository.FindAsync<Recipe>(r => r.Category.Name == StandardizeName(name));
`StandardizeName(name)` лучше вынести из выржение отдельной строкой с локальной переменной

2020-09-29 15:20 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Entities/Category.cs
> +        public virtual ICollection<Recipe> Recipe { get; private set; }
Имена коллекций должны быть во множественном значении: `Recipes`

2020-09-29 15:20 UTC, alex-geraschenko commented on task4/RecipeBook.CMD/Program.cs
> +                                recipies = await recipeController.GetRecipesInCategoryAsync(name);
Попробуйте использовать навигационное свойство `category.Recipes`

2020-09-29 15:20 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Entities/Category.cs
> +        public virtual ICollection<Category> InverseParent { get; private set; }
Это свойство лучше назвать `Children`

2020-09-29 15:20 UTC, alex-geraschenko commented on task4/RecipeBook.CMD/Program.cs
> +                                categories = await categoryController.GetCategoriesAsync(category.Id);
Попробуйте использовать навигационное свойство `category.Children`

2020-09-29 15:20 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Controllers/RecipeController.cs
> +            return UnitOfWork.Repository.FindAsync<Recipe>(r => r.Category.Name == StandardizeName(name));
А еще лучше использовать `Id` вместо имени для поиска

2020-09-29 15:20 UTC, alex-geraschenko commented on task4/RecipeBook.CMD/Program.cs
> +                    Ingredient = await ingredientController.CreateIngredientAsync(item)
Лучше добавить в контроллер метод, который принимает и сохраняет список ингридиентов за один раз вместо вызова базы в цикле

2020-09-29 15:20 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Entities/Ingredient.cs
> +        public virtual ICollection<RecipeIngredient> RecipeIngredient { get; }
Имена коллекций должны быть во множественном значении: `RecipeIngredients`

2020-09-29 15:20 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Entities/Recipe.cs
> +        public virtual ICollection<RecipeIngredient> RecipeIngredient { get; private set; }
Имена коллекций должны быть во множественном значении: `RecipeIngredients`

2020-09-29 15:20 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/Config/IngredientConfig.cs
> +                   .HasName("UQ__Ingredie__A1B2F1CC445D2F03")
Имя индекса указывать не нужно

2020-09-29 15:20 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/Config/RecipeConfig.cs
> +                .HasColumnType("text");
Вмето типа `text` лучше использовать `nvarchar(max)`, который идет по умочанию

2020-09-29 15:20 UTC, alex-geraschenko commented on task4/RecipeBook.Infrastructure/Data/RecipeBookContext.cs
> +            modelBuilder.ApplyConfiguration(new IngredientConfig());
А куда делся вызов этого метода у базового класса ?

2020-09-29 15:29 UTC, XRicko commented on task4/RecipeBook.Infrastructure/Data/Config/IngredientConfig.cs
> +                   .HasName("UQ__Ingredie__A1B2F1CC445D2F03")
Пропустил, когда убирал такие случаи

2020-09-29 16:15 UTC, XRicko commented on task4/RecipeBook.CMD/Program.cs
> +                                recipies = await recipeController.GetRecipesInCategoryAsync(name);
Действительно, так намного проще и читабельнее получается

2020-09-29 18:03 UTC, XRicko commented on task4/RecipeBook.CMD/Program.cs
> +                    Ingredient = await ingredientController.CreateIngredientAsync(item)
Но у меня же тут проверка на дубликаты, в методе `CreateIngredientAsync`. Поэтому я и перебираю каждый элемент в цикле

2020-09-29 18:12 UTC, XRicko commented on task4/RecipeBook.Infrastructure/Data/RecipeBookContext.cs
> +            modelBuilder.ApplyConfiguration(new IngredientConfig());
А его и не было 😅

2020-10-01 08:26 UTC, alex-geraschenko requested changes
Проверьте все исключения. У Вас неправильно стоят значения аргументов. Имя параметра должно идти первым, а сообщение об ошибке вторым: https://docs.microsoft.com/en-us/dotnet/api/system.argumentnullexception.-ctor?view=netcore-3.1#System_ArgumentNullException__ctor_System_String_System_String

2020-10-01 08:26 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Entities/Category.cs
> +        public virtual Category Children { get; private set; }
Вы не те свойства переименовали. Одиночная категория должна быть `Parent`, а список подкатегорий должен быть `Children`.

2020-10-01 08:26 UTC, alex-geraschenko commented on task4/RecipeBook.CMD/Program.cs
> +                    Ingredient = await ingredientController.CreateIngredientAsync(item)
Не самое удачное решение. Проверку лучше делать при вводе данных

2020-10-01 10:38 UTC, XRicko commented on task4/RecipeBook.Core/Entities/Category.cs
> +        public virtual Category Children { get; private set; }
🤦‍♂️

2020-10-03 10:22 UTC, XRicko commented on task4/RecipeBook.CMD/Program.cs
> +                    Ingredient = await ingredientController.CreateIngredientAsync(item)
Хм, просто `CreateIngredientAsync` не просто проверяет на дубликаты и не создает их. Он обращается к базе данных и если этот ингредиент уже там есть, то он возвращает уже существующий, чтобы потом связать его с рецептом

2020-10-05 19:46 UTC, alex-geraschenko requested changes

2020-10-05 19:46 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Controllers/RecipeController.cs
> +                throw new ArgumentException("This recipe already exists", nameof(recipe));
Неправильно стоят значения аргументов.

2020-10-05 19:46 UTC, alex-geraschenko commented on task4/RecipeBook.CMD/Program.cs
> +                    Ingredient = await ingredientController.CreateIngredientAsync(item)
Хорошо. Исправить данную ситуацию будет достаточно сложно и много придется переделывать. Пока оставляйте как есть. На будущее постарайтесь продумывать логику приложения так, чтобы максимально уйти от запросов к базе в циклах

2020-10-05 22:32 UTC, XRicko commented on task4/RecipeBook.Core/Controllers/RecipeController.cs
> +                throw new ArgumentException("This recipe already exists", nameof(recipe));
Я сначала начал переделывать и это, но потом наткнулся на документацию и, насколько я понял, то не везде порядок одинаковый. Для `ArgumentException` в [документации](https://docs.microsoft.com/en-us/dotnet/api/system.argumentexception.-ctor?view=netcore-3.1#System_ArgumentException__ctor_System_String_System_String_) указано как и у меня

2020-10-06 11:16 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Controllers/RecipeController.cs
> +                throw new ArgumentException("This recipe already exists", nameof(recipe));
Да, действительно для этого исключения другая сигнатура.

2020-10-06 16:37 UTC, alex-geraschenko requested changes

2020-10-06 16:37 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Exceptions/RecipeExistsException.cs
> +        public RecipeExistsException(string recipeName)
Кастомные исключения должны содержать 3 дефолтных конструктора https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-create-user-defined-exceptions

2020-10-06 16:37 UTC, alex-geraschenko commented on task4/RecipeBook.Core/Exceptions/ImpossibleDurationException.cs
> +        public ImpossibleDurationException(double duration)
Кастомные исключения должны содержать 3 дефолтных конструктора https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-create-user-defined-exceptions

2020-10-06 19:27 UTC, alex-geraschenko requested changes
Хорошо. Можно мержить

2020-10-06 19:27 UTC, alex-geraschenko approved these changes

2020-10-06 21:17 UTC, merged