Tasks/task5
XRicko/altexsoft-lab-2020 pull request #6
Opened 2020-10-06 21:18 UTC by XRicko

2020-10-07 05:27 UTC, serhii-shkodenko requested changes

2020-10-07 05:27 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            Assert.NotSame(expected, actual);
В Вашем варианте теста эта проверка будет срабатывать всегда. Здесь лучше сравнить, что фактический результат содержит ожидаемое имя категории.

2020-10-07 05:27 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync<Category>(It.IsAny<string>()))
Во всех тестах, Вы создаете одинаковые моки, имеет смысл их создание вынести в конструктор, а непосрдественно в тестах их уже настроить. Просмотрите и поправьте для всех тестов пожалуйста.

2020-10-07 05:27 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            unitOfWorkMock.Setup(x => x.Repository)
Имеет смысл добавить и поведенческие проверки, как Вы сделали в других местах.

2020-10-07 06:05 UTC, serhii-shkodenko requested changes

2020-10-07 06:05 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            unitOfWorkMock.Setup(x => x.Repository)
Для свойств нагляднее использовать `SetupGet()`.

2020-10-07 06:05 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync<Category>(It.IsAny<string>()))
В этом тесте Вам нужно сделать два Setup() для этого мока. Первый для проверки существования категории, второй - для проверки существования родительской категории. 

Для того чтобы различить вызовы, используйте не дженериковые аргументы `It.IsAny<T>`, а конкретные. Соответственно Вы тогда сможете вернуть из метода разные данные. В блоке Assert нужно будет проверить, что из контроллера вернулась категория с `parent.Id`, который Вы задали в одном из Ваших expected объектов.

2020-10-07 06:05 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +                .ReturnsAsync(It.IsAny<Category>());
`It` используется для фильтрации аргументов, которые Вы передает в метод. Здесь это неправомерное использование. В коде вы ожидаете определенный результат или его отсутствие, поэтому `ReturnsAsync() `нужно настроить соответствующим образом. Просмотрите весь код и поправьте.

2020-10-07 06:13 UTC, serhii-shkodenko requested changes

2020-10-07 06:13 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            var controller = new CategoryController(unitOfWorkMock.Object);
Контроллер Вы тоже создается в каждом тесте. Это можно вынести в конструктор теста. Это сократит доблирование кода. Поправьте для всех тестов, пожалуйста.

2020-10-07 14:03 UTC, XRicko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync<Category>(It.IsAny<string>()))
Но ведь у меня в этом тесте метод `GetAsync` возвращает одно значение для любого аргумента - `null`. Может, Вы имели ввиду тест `CreateCategoryAsync_ShouldReturnNewSubCategoryToExistingParent`? Там уже добавил второй `Setup()`

2020-10-07 14:57 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync<Category>(It.IsAny<string>()))
Детальнее посмотрел на Ваш метод `CreateCategoryAsync()`. Код в контроллере не возвращает `parent.Id` только что созданной родительской категории, верней, возвращает, но всегда дефолтное значение, поэтому в этой части часть своего коммента снимаю, Вам попросту не с чем сравнивать. Если такое поведение не проектировалось, поправьте. При этом можно добавить проверку возвращаемого имени категории:

`Assert.Equal(expectedCategoryName, category.Name);`

2020-10-07 14:57 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync<Category>(It.IsAny<string>()))
Вот мой вариант теста, где я показываю, как можно более предметно протестировать Ваш код. Обратите внимание, что я не использую дженериковые аргументы `It.IsAny<T>`.  
```
        private Mock<IRepository> _respositoryMock;
        private Mock<IUnitOfWork> _unitOfWorkMock;
        private CategoryController _controller;

        public CategoryControllerTests()
        {
            _respositoryMock = new Mock<IRepository>();
            _unitOfWorkMock = new Mock<IUnitOfWork>();

            _controller = new CategoryController(_unitOfWorkMock.Object);
        }

        [Fact]
        public async Task CreateCategoryAsync_ShouldAddParent()
        {
            // Arrange
            var parentName = "Soups";
            var categoryName = "Hot";

            _respositoryMock.Setup(x => x.GetAsync<Category>(StandardizeName(categoryName)))
                .ReturnsAsync((Category)null);

            _respositoryMock.Setup(x => x.GetAsync<Category>(StandardizeName(parentName)))
                .ReturnsAsync((Category)null);

            _respositoryMock.Setup(x => x.AddAsync(It.Is<Category>(category => category.Name == StandardizeName(parentName))));

            _unitOfWorkMock.SetupGet(x => x.Repository)
                .Returns(_respositoryMock.Object);

            var expectedCategoryName = string.Join(" ", (StandardizeName(categoryName) + " " + StandardizeName(parentName)).Split(' ').Distinct());

            // Act
            var category = await _controller.CreateCategoryAsync(categoryName, parentName);

            // Assert
            _respositoryMock.Verify();
            _unitOfWorkMock.VerifyGet(x => x.Repository, Times.AtLeast(2));

            Assert.Equal(expectedCategoryName, category.Name);
        }

        protected string StandardizeName(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
                return null;

            return CultureInfo.CurrentCulture.TextInfo.ToTitleCase(name.ToLower()).Trim();
        }
```

2020-10-07 14:57 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync<Category>(It.IsAny<string>()))
Из-за того, что Вы передаете в методы контроллера имена категорий после обработки в методе `StandardizeName()`, мне пришлось скопировать его в файл теста. Это указывает на то, что его нужно вынести в отдельное место, чтобы не дубировать.

2020-10-07 15:10 UTC, XRicko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync<Category>(It.IsAny<string>()))
> Детальнее посмотрел на Ваш метод `CreateCategoryAsync()`. Код в контроллере не возвращает `parent.Id` только что созданной родительской категории, верней, возвращает, но всегда дефолтное значение, поэтому в этой части часть своего коммента снимаю, Вам попросту не с чем сравнивать. Если такое поведение не проектировалось, поправьте. При этом можно добавить проверку возвращаемого имени категории:
> 
> `Assert.Equal(expectedCategoryName, category.Name);`

Работа с Id происходит при добавлении сущности. Метод `AddItemAsync` в `ControllerBase`. В последнем коммите я все же сравниваю ожидаемый `Id` c `category.Id`.

2020-10-07 15:15 UTC, XRicko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync<Category>(It.IsAny<string>()))
> Обратите внимание, что я не использую дженериковые аргументы `It.IsAny<T>`.

Разве так плохо использовать `It.IsAny<T>`? 

>             _respositoryMock.Setup(x => x.GetAsync<Category>(StandardizeName(categoryName)))
>                 .ReturnsAsync((Category)null);
> 
>             _respositoryMock.Setup(x => x.GetAsync<Category>(StandardizeName(parentName)))
>                 .ReturnsAsync((Category)null);

Например, зачем тут делать 2 по сути одинаковых `Setup()`? Ведь они отличаются только именем категории и возвращают одно и то же.

2020-10-07 15:23 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync<Category>(It.IsAny<string>()))
Я вызвал Ваш метод с произвольной строкой и тест не упал, а лучше чтобы упал. Иногда без `It.IsAny<T>` не обойтись, но применяя его Вы не проверяете, что заходит в качесттве аргумента в Ваш метод. 

`var category = await UnitOfWork.Repository.GetAsync<Category>("New category name");`

2020-10-07 15:28 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync<Category>(It.IsAny<string>()))
Я существенно сократил Ваш метод, и тест CreateCategoryAsync_ShouldAddParent() не упал.
![simplified_method](https://user-images.githubusercontent.com/69808191/95352417-e4cd2e00-08ca-11eb-8ef2-effb81e36126.jpg)

2020-10-07 15:41 UTC, XRicko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync<Category>(It.IsAny<string>()))
> Я вызвал Ваш метод с произвольной строкой и тест не упал, а лучше чтобы упал. Иногда без `It.IsAny<T>` не обойтись, но применяя его Вы не проверяете, что заходит в качестве аргумента в Ваш метод.
> 
> `var category = await UnitOfWork.Repository.GetAsync<Category>("New category name");`

Ну в принципе, нет же каких-то правил наименования категорий, по сути имя может быть любым :)   
Хорошо, я просмотрю использование дженериков в других тестах

2020-10-07 16:02 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync<Category>(It.IsAny<string>()))
Это не правила наименования категорий. С данными производится определенная работа. Аргументы, которые передаются в метод контроллера должны быть корректно переданы как аргументы во внутренние методы. Это важная часть бизнес логики. А вы ее не проверяете, на моем скрине это наглядно видно.

2020-10-07 18:32 UTC, XRicko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync<Category>(It.IsAny<string>()))
Хорошо, я понял суть. Вроде бы исправил, где мог

2020-10-15 21:44 UTC, serhii-shkodenko requested changes
В целом тесты уже хороши. Осталось подправить мелочи. Остальные два контроллера просмотрю в пятницу.

2020-10-15 21:44 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            Assert.NotSame(expected, actual);
Еще раз отмечу, что эта проверка не имеет смысла, так как Вы сравниваете объект, созданный в рамках тестового сценария с результатом, который создается внутри тела метода. Если бы объект возвращался из метода-стаба, тогда можно было бы проверять эти объекты с помощью `Assert.Same()`. Удалите эту проверку.

2020-10-15 21:44 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/ControllerBaseTests.cs
> +            controller = new IngredientController(unitOfWorkMock.Object);   // Because ControllerBase is abstract and IngredientController is the simplest controller
Это один из возможных подходов для тестирования абстрактного класса. Однако более наглядным будет унаследоваться от этого базового класса, реализовать только требуемый минимум функционала и уже этого наследника тестировать. При этом класс с тестами я бы все равно назвал `ControllerBaseTests`. Видимость этого класса лучше ограничить тестовым проектом.

2020-10-15 21:44 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            var expected = new Category(categoryName);
Вам этот объект на самом деле не нужен, Вы его используте только, чтобы обратиться потом к его свойству `Name`. Удалите эту переменную, достаточно будет сравнить `categoryName` с `actual.Name`.

2020-10-15 21:44 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Verify(x => x.AddAsync(It.Is<Category>(x => x.Name == categoryName)), Times.Never);
Аналогично, проверки вызова этого метода здесь быть не должно, он в базоввом классе, его нужно проверить отдельно. Удалите, пожалуйста.

2020-10-15 21:44 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAllAsync<Category>())
То что Вам пришлось стабить методы в базовом классе, меня натолкнуло на мысль, что возможно стоило бы вынести методы из него в `UnitOfWork`, а `ControllerBase` удалить. Тогда Вам здесь было бы достаточно застабить метод в моке. Однако править ничего не нужно, просто поделился наблюдением.

2020-10-15 21:44 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/ControllerBaseTests.cs
> +            var expected = GetSampleData();
Перепишите пожалуйста Вот так:
```
var expected = GetSampleData();

repoMock.Setup(x => x.GetAllAsync<Ingredient>())
                .ReturnsAsync(expected);
```

2020-10-15 21:44 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/ControllerBaseTests.cs
> +            Assert.True(actual != null);
Ваш код не предполагает возврата `null`, поэтому в этой проверке нет смылса. Ее можно без зазрения совести удалить.

2020-10-15 21:44 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/ControllerBaseTests.cs
> +            Assert.Equal(expected.FirstOrDefault().Name, actual.FirstOrDefault().Name);
Из-за того что Вы не вернули из метода в моке ожидаемый список, пришлось творчеки подойти к заданию 🧠. Однако после применения фикса, указанного выше, будет достаточно `Assert.Same(expected, actual);`. Все другие Assert удалите, пожалуйста.

2020-10-15 21:44 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/ControllerBaseTests.cs
> +            repoMock.Verify(x => x.AddAsync(ingredient), Times.Once);
Остальные два Verify() тоже можно добавить. Или можно вызвать `repoMock.Verify()`, тогда будут проверены все `Setup()`.

2020-10-15 21:44 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/ControllerBaseTests.cs
> +            repoMock.Verify(x => x.AddAsync(ingredient), Times.Never);
Можно добавить, что `GetAllAsync()` тоже не вызывается.

2020-10-16 16:46 UTC, XRicko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAllAsync<Category>())
Насколько я понимаю, `UnitOfWork` должен отслеживать изменения объектов. Место ли там методам `GetItemsAsync` и `AddItemAsync`?

2020-10-18 20:29 UTC, serhii-shkodenko requested changes

2020-10-18 20:29 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/IngredientControllerTests.cs
> +            Assert.NotSame(ingredient, actual);
В этой проверке мало смысла, так как будет выполняться всегда. Удалите, пожалуйста.

2020-10-18 20:29 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/IngredientControllerTests.cs
> +            Assert.Equal(ingredient.Name, actual.Name);
Использование поля `ingredient` здесь избыточно, достаточно проверить `ingredientName` (с учетом `StandardizeName()`) и `actual.Name`.

2020-10-18 20:29 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/RecipeControllerTests.cs
> +            Assert.NotSame(recipe, actual);
Аналогично здесь, проверка избыточна. Уберите, пожалуйста.

2020-10-18 20:29 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/RecipeControllerTests.cs
> +            Assert.Equal(recipe.Name, actual.Name);
На вход в метод Вы подаете `recipeName`, поэтому будет достаточно ее сравнить с `actual.Name`.

2020-10-18 20:29 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/RecipeControllerTests.cs
> +                .ReturnsAsync(() => null);
Раз Вы настроили методы, то почему бы не добавить для них поведенческие проверки? К проверке вызова `AddAsync()` определенного количества раз, можно добавить еще `Verify()`. Этот метод Moq автоматически проверит все заданные настройки для метода-стаба.

2020-10-18 20:29 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/RecipeControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync(recipe))
Эта настройка для данного теста не нужна. Удалите, пожалуйста.

2020-10-18 20:29 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/RecipeControllerTests.cs
> +            unitOfWorkMock.Verify(x => x.SaveAsync(), Times.Never);
Эти проверки избыточны. Удалите их, пожалуйста.

2020-10-18 20:29 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/RecipeControllerTests.cs
> +            Assert.Equal(new RecipeExistsException(recipe.Name).Message, exception.Message);
Вы проверяете сообщение в исключении, создавать для этого новый объекст исключения избыточно. Сравнения стрингового значения будет в большинстве случаев достаточно.

2020-10-18 22:34 UTC, XRicko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/RecipeControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync(recipe))
Без нее тест падает. У меня же исключение при существовании рецепта, поэтому `GetAsync` должна возвращать существующий.

2020-10-20 11:47 UTC, serhii-shkodenko approved these changes
Выглядит прилично. Подождите ревью @alex-geraschenko, если Александр одобрит, смержите.

2020-10-20 11:47 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/RecipeControllerTests.cs
> +            repoMock.Setup(x => x.GetAsync(recipe))
Да, действительно.

2020-10-20 11:47 UTC, serhii-shkodenko commented on task5/tests/RecipeBook.UnitTests/RecipeBook.Core.Tests/CategoryControllerTests.cs
> +            repoMock.Setup(x => x.GetAllAsync<Category>())
Вы правы, им там не место.

2020-10-21 11:36 UTC, alex-geraschenko commented
В общем выглядит хорошо! Я бы еще добавил тесты для `StandardizeName`, чтобы читая тесты было понятно, что он делает

2020-10-21 11:37 UTC, alex-geraschenko commented
И нужно разобраться с конфликтами при мерже

2020-10-21 12:32 UTC, XRicko commented
Хорошо, сейчас попробую сделать тесты для `StandardizeName`. С конфликтами разберусь

2020-10-21 12:55 UTC, XRicko commented
Тесты добавил. Можно мерджить?

2020-10-21 13:04 UTC, alex-geraschenko approved these changes
Хорошо. Можно мержить

2020-10-21 13:06 UTC, merged