Tasks/task6
XRicko/altexsoft-lab-2020 pull request #7
Opened 2020-10-21 13:15 UTC by XRicko

2020-10-21 17:46 UTC, alex-geraschenko commented
Не надо копировать весь код в новую папку. Нужно было только добавить новый проект в существующий солюшен. Иначе нам с Сергеем придется перепроверять весь солюшен заново, а это в Вашем случае 100 файлов. Уважайте время других

2020-10-21 17:55 UTC, XRicko commented
Ой, прошу прощения. Тогда получается, что папка `task6` не нужна и новый проект будет в `task5`?

2020-10-21 17:57 UTC, alex-geraschenko commented
> Ой, прошу прощения. Тогда получается, что папка `task6` не нужна и новый проект будет в `task5`?

да, все верно

2020-10-21 17:57 UTC, XRicko commented
Хорошо, сейчас поправлю

2020-10-21 18:12 UTC, XRicko commented
Исправил

2020-10-27 18:48 UTC, alex-geraschenko requested changes
Не выполнено условие задания:

> Для каждой сущности должны быть страницы вывода списка, добавления/редактирования и страница детальной информации

2020-10-27 18:48 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Index.cshtml.cs
> +        public string Name { get; set; }
Зачем это свойство?

2020-10-27 18:48 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Forms/AddRecipe.cshtml
> +@model RecipeBook.Web.Pages.Forms.AddRecipeModel
Вместо одной папки `Forms` лучше разделять по фичам: `Categories`, `Ingredients`, `Recipes` и т.д. и складывать файлы соответствующие файлы в эти папки.

2020-10-28 11:39 UTC, XRicko commented
> Не выполнено условие задания:
> 
> > Для каждой сущности должны быть страницы вывода списка, добавления/редактирования и страница детальной информации

Для вывода списков у меня страницы есть, для добавление рецепта тоже. Добавление отдельно категорий и ингредиентов в логике программы не заложено было. Оно добавляется вместе с рецептом, если нужно. Следует реализовать? Редактирование обязательно? У Вас написано `добавление/редактирование`, я подумал, что что-то из этого надо. Детальная информация для категорий и ингредиентов у меня это рецепты, связанные с ними.

2020-10-28 12:39 UTC, XRicko commented on task5/RecipeBook.Web/Pages/Index.cshtml.cs
> +        public string Name { get; set; }
Забыл убрать

2020-10-28 13:11 UTC, alex-geraschenko commented
> > Не выполнено условие задания:
> > > Для каждой сущности должны быть страницы вывода списка, добавления/редактирования и страница детальной информации

> Для вывода списков у меня страницы есть, для добавление рецепта тоже. Добавление отдельно категорий и ингредиентов в логике программы не было заложено. Оно добавляется вместе с рецептом, если нужно. 
> Следует реализовать?

Да

> Редактирование обязательно? У Вас написано `добавление/редактирование`, я подумал, что что-то из этого надо. 

Да, обязательно. Добавление и редактирование может быть разными страницами, а может быть одной, поэтому через `/`.

> Детальная информация для категорий и ингредиентов у меня это рецепты, связанные с ними.

А как посмотреть какие есть подкатегории у конкретной категории?

2020-10-28 13:27 UTC, XRicko commented
> > Детальная информация для категорий и ингредиентов у меня это рецепты, связанные с ними.
> 
> А как посмотреть какие есть подкатегории у конкретной категории?

Страница категорий отображается в виде карточек и выглядит так: 

![image](https://user-images.githubusercontent.com/48753171/97440672-6f380900-1930-11eb-9591-c278b8512bc0.png)

Весь текст в карточках это ссылки, которые при клике обрабатываются по-разному: если у подкатегории есть еще свои дети, то отобразится такая же карточка с новым наполнением (своими детьми), а если у выбранной подкатегории нет детей, то Вас перенаправит на страницу с рецептами в этой категории. Заголовок карточки всегда перенаправляет Вас на страничку с рецептами.

2020-10-28 14:02 UTC, alex-geraschenko commented
> > > Детальная информация для категорий и ингредиентов у меня это рецепты, связанные с ними.
> > 
> > 
> > А как посмотреть какие есть подкатегории у конкретной категории?
> 
> Страница категорий отображается в виде карточек и выглядит так:
> 
> ![image](https://user-images.githubusercontent.com/48753171/97440672-6f380900-1930-11eb-9591-c278b8512bc0.png)
> 
> Весь текст в карточках это ссылки, которые при клике обрабатываются по-разному: если у подкатегории есть еще свои дети, то отобразится такая же карточка с новым наполнением (своими детьми), а если у выбранной подкатегории нет детей, то идет перенаправление на страницу с рецептами в этой категории. Заголовок карточки всегда перенаправляет на страничку с рецептами.

Значит у Вас есть детальная информация по категориям отдельно от рецептов

2020-11-05 19:10 UTC, alex-geraschenko requested changes

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.CMD/Program.cs
> +                            if (rec is object)
Это не корректная проверка. Чем Вас не устроил вариант `rec != null`? Если не хотите испольовать `!=`, то можно написать `!(rec is null)`. Пожалуйста, поправьте во всех местах

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.Core/Controllers/CategoryController.cs
> +            string categoryName = parentName is object ? name.StandardizeName() + " " + parentName.StandardizeName() : name.StandardizeName();
Хранение имени родительской категории в подкатегории нарушает 3 нормальную форму, т.к. у Вас появляется дублирование данных.

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.Core/Controllers/CategoryController.cs
> +        private async Task<Category> GetOrCreateSubcategoryAsync(string name, string parentName)
Пожалуйста, уберите разные методы для создания родительской и под- категорий. Разница между ними только лишь в том, какой будет `Parent` (`ParentId`) и все

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.Core/Controllers/RecipeController.cs
> +            UnitOfWork.Repository.FindAsync<Recipe>(r => r.Category == null);
А как у Вас может быть ситуация, что рецепт без категории, если это противоречит изначальному условию?

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.Core/Entities/Recipe.cs
> +                else
Если в блоке `if` у Вас `return` или `throw`, то необходимости в `else` нет, а значит можно убрать уровень вложености. Пожалуйста, поменяйте по всему коду.

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Categories/CategoriesList.cshtml
> +                        <a class="text-muted text-decoration-none" asp-page="Forms/AddCategory" asp-page-handler="Category" asp-route-id="@category.Id">Edit</a>
Не правильно указан `asp-route-id`. Должен быть `@subcategory.Id`

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Categories/CategoriesList.cshtml.cs
> +        public IActionResult RedirectToRecipes(string categoryName)
Этот метод у Вас используется только внутри класса. В этом случае он должен быть `private`

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Categories/CategoriesList.cshtml.cs
> +            return RedirectToRecipes(categoryName);
Это логически не правильно. При нажатии на имя категории ожидается переход в эту категорию для просмотра подкатегорий. Для перехода лучше добавить еще ссылку, которая будет прямо вести на список рецептов.

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Categories/CategoriesList.cshtml.cs
> +            var category = await categoryController.GetByNameAsync<Category>(categoryName);
В качестве фильтра вместо имени категории лучше использовать `Id`

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Categories/Forms/AddCategory.cshtml
> +@model RecipeBook.Web.Pages.Categories.Forms.AddCategoryModel
При разделении по фичам нет смысла выделять одну страницу в отдельную папку `Forms`. Поправьте для всех сущностей

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Categories/Forms/AddCategory.cshtml
> +        <input type="text" asp-for="ParentName" value="@Model.Category?.Parent?.Name" class="form-control" placeholder="Enter parent category" />
Это логически неверно. Задание родительской категории должно быть автоматически на основании текущей категории.

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Recipes/Forms/AddRecipe.cshtml
> +        <input type="text" asp-for="CategoryName" value="@Model.Recipe?.Category?.Name" class="form-control" placeholder="Enter category" required />
Вместо того, чтобы вручную указывать имя категории, лучше привязываться уже к существующим. Либо с помощью выпадающего списка `<select>`, либо можно добавить ссылку на страницу добаления рецепта из категории с добавлением `category.Id` через `asp-route-`

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Recipes/Forms/AddRecipe.cshtml
> +        <label asp-for="ParentCategoryName">Parent category name</label>
Забудте Вы про добаление родительской категории

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Recipes/Forms/AddRecipe.cshtml
> +        @Html.TextAreaFor(m => m.Ingredients, new { @class = "form-control", @placeholder = "Enter ingredients", required = "required" })
Вместо просто текста, лучше использовать список `<input type="checkbox">` со уже созданными ингридиентами

2020-11-05 19:10 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Recipes/Forms/AddRecipeIngredients.cshtml
> +@model RecipeBook.Web.Pages.Forms.AddRecipeIngredientsModel
Если последуете рекомендациям к `AddRecipe`, то в этой странице отпадет необходимость

2020-11-06 12:00 UTC, XRicko commented on task5/RecipeBook.CMD/Program.cs
> +                            if (rec is object)
Почему не корректная? Разработчик компилятора C# в своем [твите](https://twitter.com/jaredpar/status/1115019017297596416?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1115019017297596416%7Ctwgr%5Eshare_3&ref_url=https%3A%2F%2Fcdn.embedly.com%2Fwidgets%2Fmedia.html%3Ftype%3Dtext2Fhtmlkey%3Da19fcc184b9711e1b4764040d3dc5c07schema%3Dtwitterurl%3Dhttps3A%2F%2Ftwitter.com%2Fjaredpar%2Fstatus%2F1115019017297596416image%3Dhttps3A%2F%2Fi.embed.ly%2F1%2Fimage3Furl3Dhttps253A252F252Fpbs.twimg.com252Fprofile_images252F985600797068021760252FlqFDpEIj_400x400.jpg26key3Da19fcc184b9711e1b4764040d3dc5c07) советует такой вариант. Решил поменять старый из-за того, что операторы сравнения могут быть переопределены и проверки ими советуют не делать

2020-11-06 18:19 UTC, alex-geraschenko commented on task5/RecipeBook.CMD/Program.cs
> +                            if (rec is object)
Потому что, на практике такой записью практически никто не пользуется. Поэтому у многих разработчиков возникнут сложности (пусть и минимальные) в понимании Вашего кода. Такая запись заставляет задуматься, что именно тут происходит. Не все читают твитер разработчиков компилятора. В C# 9 даже появилась конструкция `rec is not null`, которая более очевидна, чем `rec is object`. Еще вариант: Вы можете инвертировать проверку, где это возможно, чтобы вместо `if (rec is object)` было `if (rec is null)`. Часто это помогает убрать один уровень вложености кода, что также добавляет ему читабельности

2020-11-06 18:24 UTC, alex-geraschenko commented on task5/RecipeBook.CMD/Program.cs
> +                            if (rec is object)
Если почитать ветку под приведенным Вами твитом, то там будет еще один аргумент не использовать `rec is object` - https://twitter.com/jnyrup/status/1115526287840415744

2020-11-06 19:15 UTC, XRicko commented on task5/RecipeBook.CMD/Program.cs
> +                            if (rec is object)
Я сначала и хотел использовать `rec is not null`, но потом дочитал, что это из C# 9. 
Хорошо, я просмотрю использование `is object` и поправлю

2020-11-07 18:01 UTC, XRicko commented on task5/RecipeBook.Core/Controllers/RecipeController.cs
> +            UnitOfWork.Repository.FindAsync<Recipe>(r => r.Category == null);
И правда, оно мне нужно было только для инициализации коллекции

2020-11-07 21:30 UTC, XRicko commented on task5/RecipeBook.Web/Pages/Categories/Forms/AddCategory.cshtml
> +        <input type="text" asp-for="ParentName" value="@Model.Category?.Parent?.Name" class="form-control" placeholder="Enter parent category" />
Не совсем понимаю, что именно имеется ввиду. Как из имени категории можно узнать родительскую? Или что Вы имеете ввиду под "текущей категорией"?

2020-11-10 12:23 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Categories/Forms/AddCategory.cshtml
> +        <input type="text" asp-for="ParentName" value="@Model.Category?.Parent?.Name" class="form-control" placeholder="Enter parent category" />
Вам не нужно задавать родительскую категорию на форме. У Вас в базе есть связка категории с родительской через `ParentId`

2020-11-10 12:32 UTC, XRicko commented on task5/RecipeBook.Web/Pages/Categories/Forms/AddCategory.cshtml
> +        <input type="text" asp-for="ParentName" value="@Model.Category?.Parent?.Name" class="form-control" placeholder="Enter parent category" />
Да, это ведь в том случае, если выбирать из списка существующих, как на странице добавить рецепт. А как создать новую категорию без родительской?

2020-11-10 16:55 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Categories/Forms/AddCategory.cshtml
> +        <input type="text" asp-for="ParentName" value="@Model.Category?.Parent?.Name" class="form-control" placeholder="Enter parent category" />
Со списка категорий по нажатии на имя категории переходить не на список рецептов, а внутрь этой категории, и там иметь возможность добавить категорию с текущей (в которую перешли) в качестве родительской.
При этом для перехода на список рецептов переходить по отдельной кнопке

2020-11-19 17:33 UTC, alex-geraschenko requested changes
Пожалуйста, решите еще мерж-конфликты

2020-11-19 17:33 UTC, alex-geraschenko commented on task5/RecipeBook.Core/Controllers/CategoryController.cs
> +            string categoryName = parentName is null ? name.StandardizeName() : name.StandardizeName() + " " + parentName.StandardizeName();
Вы наверное не увидели мой комментарий по поводу хранения имени родительской категории вместе с текущей категорией. Это противоречит 3 нормальной форме и приводит к дублированию данных.
Храните только имя текущей категории и все. Тогда Вам не нужна будет логика поиска и удаления дубликатов и т.п.

2020-11-19 17:33 UTC, alex-geraschenko commented on task5/RecipeBook.Core/Controllers/RecipeController.cs
> +        public Task<IEnumerable<Recipe>> GetRecipesInCategoryAsync(int categoryId) =>
Всместо этого метода можно использовать навигационные свойства. Например, `Category.Recipes`

2020-11-19 17:33 UTC, alex-geraschenko commented on task5/RecipeBook.Web/Pages/Recipes/AddRecipe.cshtml.cs
> +                var recipeIngredient = new RecipeIngredient();
Предыдущий вариант с инициализацией более предпочтителен.

2020-11-19 17:36 UTC, XRicko commented on task5/RecipeBook.Web/Pages/Recipes/AddRecipe.cshtml.cs
> +                var recipeIngredient = new RecipeIngredient();
Его дебажить сложнее. Я и хотел потом поменять обратно, как с ошибкой разберусь, но забыл. Сейчас изменю

2020-11-19 18:20 UTC, XRicko commented on task5/RecipeBook.Core/Controllers/CategoryController.cs
> +            string categoryName = parentName is null ? name.StandardizeName() : name.StandardizeName() + " " + parentName.StandardizeName();
Видел, но подумал, что Вы об отдельном методе, который только и делал, что формировал имя. Поменял на `parentId`, чтобы создавать связь. Это ведь не нарушает 3 форму?

2020-11-23 19:24 UTC, alex-geraschenko requested changes

2020-11-23 19:24 UTC, alex-geraschenko commented on task5/RecipeBook.Core/Controllers/ControllerBase.cs
> +                entity.Id = items is null || !items.Any() ? 1 : items.OrderBy(i => i.Id).Last().Id + 1;
Только щас обратил внимание, что Вы вручную вычисляете следующий `Id`. Все таки лучше так не делать, а перенести это на уровне базы. В конфигурациях стоит указать это поле как первичный ключ с автоинкрементом.

2020-11-23 21:55 UTC, XRicko commented on task5/RecipeBook.Core/Controllers/ControllerBase.cs
> +                entity.Id = items is null || !items.Any() ? 1 : items.OrderBy(i => i.Id).Last().Id + 1;
У меня, кстати, сначала и было с автоинкрементом. А потом я изменил, но не помню почему

2020-11-24 11:25 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-11-24 11:56 UTC, merged